### PR TITLE
Updated package name

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by stof** [comment]
We should add `replace` for the older name too

**Comment by Nyholm** [comment]
Do we want to rename this package? Im okey with leaving it as it is. 

Do @henrikbjorn want this? If you do, Im happy to fix it.

**Comment by henrikbjorn** [comment]
It should be `stampie/stampie` no need for my name to be part of it :)

**Comment by stof** [comment]
👍 for this change.

Once merged, we need to register the package on Packagist using its new name (please add the 3 of us as maintainer on Packagist to make things simpler to manager). and then, @henrikbjorn will be able to mark the old name as abandonned on Packagist.

**Comment by stof** [comment]
@Nyholm before releasing 1.0, we should also work on migrating the bundle (also renaming the package) and stof/stampie-extra (which will move to this organization and be renamed to `stampie/extra`)

**Comment by Nyholm** [comment]
Thank you for your quick feedback.

**Comment by Nyholm** [comment]
New package submitted. `henrikbjorn/stampie` can be marked as abandonned.
https://packagist.org/packages/henrikbjorn/stampie

**Comment by henrikbjorn** [comment]
I have abandoned the one with my name and set stampie/stampie as the replacement.

**Pull request merged**
