### PR TITLE
add Mandrill subaccount support

### PR DESCRIPTION
**Pull request by fbourigault**
This allows to use the Mandrill subaccount.

Implements #92.

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you

**Comment by stof** [comment]
I would make it a constructor argument to avoid making it mutable for now though

**Comment by fbourigault** [comment]
IMHO we should add constructors to any Mailer and stop using getter/setters!

**Comment by Nyholm** [comment]
:+1:

**Comment by stof** [comment]
@fbourigault totally true (but we should probably keep the setter and getter around for easier migration)

**Comment by fbourigault** [comment]
Let's do that in a minor release. We have break enough things :P

**Pull request merged**
