### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by fbourigault**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/zDBDpJ).

### CODE REVIEW

**Comment by fbourigault** [comment]
What is the reason about closing this? In #102, StyleCI complains about code style.

**Comment by Nyholm** [comment]
I did not close this. I know it really looks like I did, but I was asleep at the time. =)

StyleCI cannot have 2 open PRs to the same organization at the same time. That is why StyleCI closed this in my name. 

I think we should merge our open PRs before doing this auto generated fix.

**Comment by fbourigault** [comment]
> StyleCI cannot have 2 open PRs to the same organization at the same time.
Didn't know about this limitation!

**Comment by Nyholm** [comment]
I reported that bug to StyleCI this weekend.

**Pull request closed without merging**
