### PR TITLE
Using PSR-4

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Great however, the relocation of the files arent a good idea.

**Comment by Nyholm** [comment]
> the relocation of the files arent a good idea.

How come?

Btw, Can you enable travis, style ci etc (or make me admin)

**Comment by henrikbjorn** [comment]
You should be an administrator now. Moving files is a BC break.

**Comment by stof** [comment]
@henrikbjorn do you actually support the case where people require files themselves instead of relying on the autoloading configuration shipped in the package ? If yes, **adding** files is a BC break... Nobody tries to provide BC for people reconfiguring the autoloader themselves without using the metadata shipped in the composer.json

**Comment by Nyholm** [comment]
Yeah, I thought I could squeze in this minor BC break before the stable release

**Comment by stof** [comment]
For Travis, the first issue is that the Stampie organization uses the third-party access policy, and Travis is not authorized. So it cannot put the status on the repo. It must be accepted by an organization owner (and I'm not one)

**Comment by Nyholm** [comment]
Correct. I think the owner got an email.

See this page: https://github.com/settings/connections/applications/f244293c729d5066cf27

**Comment by stof** [comment]
yeah, I requested access.

**Comment by henrikbjorn** [comment]
Ill give both of you owner when i get home :)
fre. 23. jun. 2017 kl. 16.04 skrev Christophe Coevoet <
notifications@github.com>:

**Comment by henrikbjorn** [comment]
I am okay with the file rename now.

You are both now "Owners"

I have approved Scrutinizer.

**Comment by Nyholm** [comment]
Thank you Henrik. 

I need one of you to decide and merge on this PR. Im fine either way. 

IIRC Symfony went from PSR-0 to PSR-4 in a minor release.

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
